name: Build Latest

on: [push,workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '8.0.*'

jobs:

  build-linux-x64:
    
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    
    steps:
      
      - run: apt-get update
      - run: apt-get install -y curl wget
      - uses: actions/checkout@v1
      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - run: apt-get install -y libicu-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev
      - run: dotnet publish BBDown -r linux-x64 -c Release -o artifact
      
      - name: Upload Artifact[linux-x64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_linux-x64
          path: artifact/BBDown

          
